### ISSUE TITLE
 jwt token安全性问题疑问

### ISSUE THREAD

**Issue by bingo235** [WizTeam/wiz-editor#10]
这是我简单阅读server.js代码后的理解，是否已经有解决方案，或者我理解错误了。

### 1. AuthMessage中的user信息未加入jwt
https://github.com/WizTeam/wiz-editor/blob/d55af5a6caecda72c760e9731725c03ee6506ad6/h5/src/custom.ts#L868
```
  const data = {
    userId,
    docId,
    appId: AppId,
    permission,
  };
```
jwt中只放入了userID，用户的displayName，avatarUrl通过AuthMessage发送，可以伪造。

### 2. jwt中的permission和AuthMessage中的permission不相同时的处理？
生成jwt时permission传入'r'，但在AuthMessage中permission传入'w'，此时服务端compareAuth函数会报错，但文档仍然可写入。

### 2. 还有个建议，部署时希望能支持前后端分离，能独立配置websocket地址和API地址，方便nginx转发。BaseURL不需要通过websocket地址来获取。
```
return e.prototype.getBaseURL = function () {
                    var e = new URL(this.url);
                    return ("wss:" === e.protocol ? "https:" : "http:") + "//" + e.host +
                        e.pathname
                }
```

**Comment by bingo235** [comment]
@wizweishijun

**Comment by WizTeam** [comment]
1. 0.0.388版本已经处理，允许jwt token增加用户头像和昵称，token设置后，无论客户端是否设置这两个值，都会使用token里面设置的头像和昵称。
2.  我们测试没问题。认证成功，是因为demo里面，认证出错的时候，回调用reauth方法。这个方法成功了。
3. demo里面为了简单将前后端放在一起了。本身支持前后端分离。前端的代码是一个纯粹的npm包，不绑定任何服务端

**Comment by bingo235** [comment]
感谢解答，今天用0.0.388测试下

**Comment by bingo235** [comment]
以上几个问题都已解决，感谢。

是否考虑将AuthMessage中的除token之外的参数去除，或者服务端不验证AuthMessage中于token不匹配的字段。

因为应用端从应用服务获取到jwt token， 拉起wiz-clinet时其实只需要传入jwt token。目前应用端需要返回token，并将token中的用户信息一并返回，其实没有必要了。
```
export interface AuthMessage {
    appId: string;
    docId: string;
    userId: string;
    permission: AuthPermission;
    token?: string;
    displayName: string;
    avatarUrl: string;
    userData?: string;
}
```

**Comment by WizTeam** [comment]
> 以上几个问题都已解决，感谢。
> 
> 是否考虑将AuthMessage中的除token之外的参数去除，或者服务端不验证AuthMessage中于token不匹配的字段。
> 
> 因为应用端从应用服务获取到jwt token， 拉起wiz-clinet时其实只需要传入jwt token。目前应用端需要返回token，并将token中的用户信息一并返回，其实没有必要了。
> 
> ```
> export interface AuthMessage {
>     appId: string;
>     docId: string;
>     userId: string;
>     permission: AuthPermission;
>     token?: string;
>     displayName: string;
>     avatarUrl: string;
>     userData?: string;
> }
> ```

目前在作为离线编辑器使用的时候，还在依赖传入进来的用户信息。我们会在以后版本考虑改进。谢谢！

**Comment by bingo235** [comment]
好的，感谢回复，编辑器做的很赞
