### ISSUE TITLE
index.html中建议加载本地字体样式

### ISSUE THREAD

**Issue by woaidianqian** [WizTeam/wiz-editor#11]
`<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>`
如果在局域网部署的话，由于不能联网会导致加载时间太慢，希望能直接把font.css文件设置成本地模式。

为知的开源协作项目是我这种小白都能部署的特别赞的项目，对于没有js基础的人来讲类似于luckysheet这种开源程序部署起来麻烦的要死，完全没有头绪，但是为知笔记真的是一键搞定，特别赞，并且复制到其他电脑还能稳定运行真的是太厉害了。

**Comment by woaidianqian** [comment]
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

**Comment by woaidianqian** [comment]
[<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>](url)

**Comment by woaidianqian** [comment]
`<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>`

**Comment by WizTeam** [comment]
这个页面是一个demo页面，真正使用的时候，编辑器是被嵌入到其他页面的，这些样式都是可以任意修改。
