### ISSUE TITLE
对firefox浏览器支持不友好

### ISSUE THREAD

**Issue by woaidianqian** [WizTeam/wiz-editor#13]
firefox quantum 62.0 32位
存在以下两个问题：1无法点击下载office文件；2在输入文字的时候，如果输入逗号，会连续出现两个逗号，并且输入的文字会有很多重复，并且页面会报错。
请问作者是否有考虑针对firefox优化的计划。

**Comment by woaidianqian** [comment]
局域网环境，没有升级Firefox

**Comment by woaidianqian** [comment]
> 你是什么环境下，为什么会使用版本这么低的firefox

就是普通的局域网环境，没有升级Firefox。

**Comment by WizTeam** [comment]
升级到最新版本firefox就可以了。
