### ISSUE TITLE
Bug report：通过api禁用视频&音频后，快速插入列表中仍存在这两项

### ISSUE THREAD

**Issue by nxjniexiao** [WizTeam/wiz-editor#19]
通过下面两个api禁用了左侧菜单中的视频和音频：
```ts
const options: EditorOptions = {
  disableVideo: true, // 禁用视频
  disableAudio: true // 禁用音频
};
```
但是通过 `/` 弹出的快速插入菜单中仍有这两个选项：
![image](https://user-images.githubusercontent.com/30365414/153110799-18ba4d83-afe5-4ee5-a411-4e2c6e40df7b.png)

demo: [disable-video-disable-audio](https://codesandbox.io/s/disable-video-disable-audio-lq4km)

**Comment by WizTeam** [comment]
0.0.577已经修复，谢谢！
