### ISSUE TITLE
won't work in WSl

### ISSUE THREAD

**Issue by TianMing2018** [WizTeam/wiz-editor#2]
按照这边文章所述,<https://mp.weixin.qq.com/s/NHA2dXgdm4zdafZD0R7-2w>,可以正常安装上插件,但是在WSL环境下无法登录账号
ps:wsl使用的是Ubuntu20.04离线安装包,公司环境,不知道是否有部分网址被禁导致无法登录的可能性

**Comment by WizTeam** [comment]
反馈位置错了
