### ISSUE TITLE
Bug report：删除编辑器中的内容后，editorDoc中有冗余数据

### ISSUE THREAD

**Issue by nxjniexiao** [WizTeam/wiz-editor#20]
demo: [冗余数据](https://codesandbox.io/s/editor-doc-r08bb?file=/src/App.tsx)
步骤：
1. 删除编辑器中的表格块。
2. 按ctrl+s保存。
3. 查看console中打印的editorDoc。
结果如图：
![image](https://user-images.githubusercontent.com/30365414/153114157-e45942cf-a9e4-4444-be3a-4144f1fbeab6.png)

**Comment by WizTeam** [comment]
这个有计划改进，谢谢！

**Comment by WizTeam** [comment]
抱歉，目前编辑器不再免费提供了，如果需要使用需要购买。具体可以联系 https://ones.cn/
