### ISSUE TITLE
是否有api隐藏菜单中的图片和office文件

### ISSUE THREAD

**Issue by nxjniexiao** [WizTeam/wiz-editor#21]
开发者，您好！
我想咨询下是否有api隐藏菜单中的图片和office文件：
![image](https://user-images.githubusercontent.com/30365414/153114407-5ef1567c-3fb1-47f7-bd90-b0f1332f2f05.png)
wiz-editor版本：0.0.540

**Comment by WizTeam** [comment]
embedUtils.getEmbedClassByType('image')!.getEmbedOptions = () => ({ menuItems: [] });
embedUtils.getEmbedClassByType('office')!.getEmbedOptions = () => ({ menuItems: [] });
