### ISSUE TITLE
Bug Report: 拖拽图片时报错target isn't the ancestor of el

### ISSUE THREAD

**Issue by nxjniexiao** [WizTeam/wiz-editor#23]
重现demo: [codesanbox](https://codesandbox.io/s/drag-image-4rjmo1?file=/src/App.tsx)

前置条件：wiz-editor的父元素是 **fixed** 布局，模拟在模态窗中使用wiz-editor的场景。
重现步骤：鼠标位于图片上时，按住鼠标左键并拖拽图片。
现象：控制台报错: target isn't the ancestor of el 。
wiz-editor版本：0.0.569

**Comment by WizTeam** [comment]
编辑器暂时不能放在fixed容器里面
