### ISSUE TITLE
wiz-editor能不能在接下来支持粘贴公式纯文本?

### ISSUE THREAD

**Issue by awehook** [WizTeam/wiz-editor#25]
在wiz-editor中粘贴公式纯文本  $a+b=c$  或者 $$a+b=c$$ 时，能识别出是公式，并正确渲染。

**Comment by tiejunhu** [comment]
我们不是一个100%面向markdown的编辑器，因此基于少量的文字，无法自动识别出这是一段markdown格式的内容。因此我们专门为此需求做了一个菜单：

右键，作为markdown粘贴即可。
