### ISSUE TITLE
颜色弹窗能增加颜色吗？

### ISSUE THREAD

**Issue by nxjniexiao** [WizTeam/wiz-editor#26]
开发者，您好！
我想咨询下，颜色弹窗中能增加颜色吗？
![image](https://user-images.githubusercontent.com/30365414/175513732-cd285e7a-bfca-4be7-afe1-31d4515bacfa.png)

**Comment by WizTeam** [comment]
抱歉，目前编辑器不再免费提供了，如果需要使用需要购买。具体可以联系 https://ones.cn/
