### ISSUE TITLE
Markdown脚注与公式换行

### ISSUE THREAD

**Issue by makefile** [WizTeam/wiz-editor#28]
目前在使用过程中发现编辑器的两个问题：

- 不支持Markdown脚注语法，例如 `[^1]: My footnote.` [^1] ，希望可以支持一下。
- 编写多行公式时如果不按规范写法加`\begin{} \end{}`，只写两个`\\`时不能自动换行，如果可以支持会更方便一些。
```
$$
a \\
b
$$
```
而在Typora等编辑器中均不存在这两个问题。

[^1]: My footnote.

**Comment by WizTeam** [comment]
抱歉，目前编辑器不再免费提供了，如果需要使用需要购买。具体可以联系 https://ones.cn/
