### ISSUE TITLE
wiz-editor npm 包部分是否有开源计划

### ISSUE THREAD

**Issue by jh244212647** [WizTeam/wiz-editor#30]
假如需要对npm包wiz-editor部分进行修改，例如目前drawio采用的引用drawio官网的编辑器方式非常卡顿。想要自己部署drawio，在wizEditor中使用，但是需要修改node module中的wiz-editor代码，这部分看着是被压缩过的，请问这里可以上传原格式的代码么，或者在哪里可以找到呢

**Comment by WizTeam** [comment]
抱歉，目前编辑器不再免费提供了，如果需要使用需要购买。具体可以联系 https://ones.cn/
