### ISSUE TITLE
server使用mysql报错application has no mysql module

### ISSUE THREAD

**Issue by l54808821** [WizTeam/wiz-editor#31]
您好，本地demo了一下觉得这个编辑器非常棒，但是项目文档似乎不是很全面。现在有如下几个问题请教
1、server短看配置是可以支持mysql 的，但是会报错application has no mysql module，
     配置如下const options = {
  enableFakeTokenApi: true, // 仅用于demo，测试和生产环境，都不要启用这个功能，具体token生成方式，请在自己的业务中实现。
  serveStatic: true, // 发布静态文件
  staticDir: path.resolve("./dist"), //静态文件目录
  database: {
    use: "mysql",
    opUse: "database",
    mysql: {
      host: "192.168.233.131",
      port: 3306,
      user: "root",
      password: "123456",
      database: "editor-doc",
      connectionLimit: 1000,
    },
  },
}

2、现在当socket服务断开时，是强制弹出alert，有什么方式可以自定义弹出组件呢

3、编辑器可以支持任务，我可以用什么方式可以拿到任务或者出发任务呢

**Comment by WizTeam** [comment]
抱歉，目前编辑器不再免费提供了，如果需要使用需要购买。具体可以联系 https://ones.cn/

**Comment by awehook** [comment]
> 抱歉，目前编辑器不再免费提供了，如果需要使用需要购买。具体可以联系 https://ones.cn/

test
