### ISSUE TITLE
wiz-editor 正式版何时可用

### ISSUE THREAD

**Issue by juejian** [WizTeam/wiz-editor#9]
有段时间没看到该项目更新了，不知何时计划发布正式版投入使用？  这个项目的设计理念，功能特性等目前在已上线的 wolai 产品中已基本实现，因此wiz-editor 发布太迟，市场使用率会降低不少。

此外，wiz-editor 为知团队是准备单独作为一个产品运营 or 会集成在为知笔记中使用?

目前为知团队分别运营**为知笔记** 和 **wiznoteLite** 2款笔记软件，用户需要2者配合使用，不断切换，不太方便。很期待用  wiz-editor 全面提升为知笔记的体验！

**Comment by WizTeam** [comment]
一直在更新，直接用npm安装编辑器就可以了，最新版本已经到0.0.365了。
编辑器已经整合到正在测试的新版本客户端中（完全重构的全平台桌面客户端），完善后将会完整替代现在的客户端和lite客户端。

wiz-editor将会作为一个独立的产品发布，方便嵌入到各种系统中（目前已经在多个业务系统中使用）。
